Repository open-hyped/hyped, pull requests merged in 2024-05, with the labels that each got.

#24 Add documentation for data pipe and processors
  docs/source/data_pipe.rst
  docs/source/data_processors.rst
  docs/source/index.rst
Labels: documentation

#27 Fix nested async event loop by using `nest_async` package.
  pyproject.toml
  src/hyped/data/processors/base.py
  tests/hyped/data/processors/base.py
  tests/hyped/data/processors/test_base.py
Labels: bug

#25 10 json decoder data processor
  pyproject.toml
  src/hyped/common/pydantic.py
  src/hyped/data/io/datasets/typed_json.py
  src/hyped/data/processors/parsers/__init__.py
  src/hyped/data/processors/parsers/json.py
  src/hyped/data/processors/parsers/repair_json.py
  tests/hyped/data/processors/parsers/__init__.py
  tests/hyped/data/processors/parsers/test_json.py
  tests/hyped/data/processors/parsers/test_repair_json.py
Labels: enhancement

#11 Feature/jinja
  docs/source/conf.py
  src/hyped/data/processors/templates/__init__.py
  src/hyped/data/processors/templates/jinja2.py
  tests/hyped/data/processors/templates/__init__.py
  tests/hyped/data/processors/templates/test_jinja2.py
Labels: enhancement

#34 32 support nesting of data pipes
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  src/hyped/data/pipe.py
  src/hyped/data/processors/base.py
  tests/hyped/data/io/datasets/test_cas.py
  tests/hyped/data/io/datasets/test_typed_json.py
  tests/hyped/data/test_graph.py
  tests/hyped/data/test_pipe.py
Labels: enhancement
